---
title: "Exploring 2021 Canadian Election"
format: html
editor: visual
---
```{r}
#### Workspace setup ####
# install.packages("tidyverse")
# install.packages("janitor")
```

```{r}
#### Preamble ####
# Purpose: Read in data from the 2021 Canadian Election and make
# a graph of the number of seats each party won.
# Author: Group 17
# Email: 
# Date: 5 September 2024
# Prerequisites: Know where to get Canadian elections data.


#simulation
library(tidyverse)
library(janitor)
simulated_data <-
  tibble(
    # Use 1 through to 151 to represent each division
    "Division" = 1:338,
    # Randomly pick an option, with replacement, 151 times
    "Party" = sample(
      x = c("Liberal", "Conservative","Bloc Quebecois", "New Democratic", "Green", "other"),
      size = 338,
      replace = TRUE
    )
  )

simulated_data
```

```{r}
#### Preamble ####
# Purpose: Downloads and saves the 2021 Canadian Election Voting Data
# Prerequisites: Have a file with the data.
write_csv(
  x = raw_elections_data,
  file = "canadian_voting.csv"
)
```

